# Generated by Django 4.0.4 on 2022-05-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
