# Generated by Django 4.0.4 on 2022-05-31 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_images_remove_product_tags_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
    ]
