# Generated by Django 4.0.4 on 2022-05-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialSidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(blank=True, max_length=255, null=True)),
                ('link_address', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.ImageField(upload_to='social_images/')),
                ('background', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Социальные сети',
            },
        ),
    ]
